language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - mysql -e 'create database circlefinder_testing;'
  - composer self-update
  - composer global require "squizlabs/php_codesniffer=*"
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - phpcs
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

notifications:
  email:
    on_success: never